### ISSUE TITLE
Список с актуальными багами FE

### ISSUE THREAD

**Issue by Izrajke** [Izrajke/quiz#14]
1. При наведении курсором на empty клетку курсор должен оставаться стрелкой по умолчанию
2. При нажатии на кнопку "Создать лобби" если возникает любая ошибка оповещаем пользователя о том, чтобы он попробовал повторить попытку позже "Что-то пошло не так, повторите попытку позже"
Оповещать можно показывая маленькую модалку, которая через 1-2 секунды пропадает

**Comment by gogsh** [comment]
Сделал то что выше. Задачу не буду закрывать - пиши баги сюда

**Comment by Izrajke** [comment]
1. При наведении курсором на isExists = false клетку курсор должен оставаться стрелкой по умолчанию
2. Выводит при нажатии на кнопку "Создать лобби" если возникает любая ошибка "NetworkError when attempting to fetch resource" нужно русский текст выводить
3. Нет переключения в режим атаки после выбора всех клеток либо после {"type":15} либо после {"type":9,"turns":[]} нужно переключать, также нужно учесть порядок ходов из {"type":9,"turns":[]}

**Comment by Izrajke** [comment]
@gogsh 

1. Переделать урлы, не делать камелКейсом

> createPack = create-pack (можно просто pack/new | pack/edit | pack/view | pack/delete)
> aboutGame = about-game (можно просто about или about-us)

**Comment by gogsh** [comment]
2. Дисконектиться от сокета при закрытии вкладки главной страницы

**Comment by gogsh** [comment]
3. поле пароль сделать необезательным(при создании лобби)

**Comment by gogsh** [comment]
4. Кнопка создания пака
5. Инициализация приложения (сделать асинхронной)

**Comment by gogsh** [comment]
поправить время в сообщении
