### ISSUE TITLE
(FE) Добавить обработку сокета на Home странице

### ISSUE THREAD

**Issue by Izrajke** [Izrajke/quiz#27]
1. Обрабатывать сообщения из чата type 100, должна быть возможность скролла, последнее сообщение должно отображаться внизу блока (как в обычном чате) 
2. Обрабатывать сообщения type 101, информация об ожидающих игры лобби, подумать про то как будет выглядеть список с большим кол-во лобби (возможно добавить скролл)

**Comment by gogsh** [comment]
Добавить стили скролла для mozila

**Comment by Izrajke** [comment]
@gogsh Завяжись для 101 на бэк после можно будет закрыть задачу
